### ISSUE TITLE
Align implementation and tests against latest version of spec.

### ISSUE THREAD

**Issue by laserpants** [sqids/sqids-cpp#2]

**Comment by laserpants** [comment]
Hi @4kimov! Just FYI: This version is now updated to match the new spec. Let me know if you think I've missed anything. The tests are [here](https://github.com/sqids/sqids-cpp/tree/main/tests).

**Comment by 4kimov** [comment]
Hi @laserpants 👋

The tests look great 💪 Thank you for getting C++ on board, great job with this!
Do the examples look good, or should we adjust something? https://sqids.org/cpp

**Comment by laserpants** [comment]
Thanks,

The examples look good. I'll try to finish the changes on the Haskell
version next.
